### ISSUE TITLE
[BUG] VNAV not coming on 

### ISSUE THREAD

**Issue by k8cpachuck** [saltysimulations/salty-747#281] opened 2021-08-04 03:56 UTC
**Version of the mod**

4.0 stable

**Describe the bug**

I take off from the runway, preset starting Altitude, and go to press the RNAV AND VNAV buttons. RNAV works, VNAV does not come on at all.And no, it's not my setup either.

**To Reproduce**
1. START AT RUNWAY.
2. SET ALTITUDE
3. TURN ON VNAV AND RNAV
4. 

**Expected behavior**

VNAV TO COME ON

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?

MOD

Your Discord:

Comments: I don't appreciate the attitudes of some of the moderators here. I'm 49, not 15. please treat me as such... Don't like being talked to like I'm stupid.

**Comment by giridat** [comment] 2021-08-04 04:13
Hello, we have no idea (at least I don't) who has been at bad attitude with you. 

Coming to the problem I'd advise you to look at youtube tutorials on how to fly using LNAV and VNAV because it is not RNAV. 

For VNAV to work to you need to setup a route and setup your FMC only then it enables LNAV/VNAV. 

Use the discord for further information on this. 

[ To be closed as not a bug ]

**Comment by ninjomcs** [comment] 2021-08-04 15:17
hey, according to your "to reproduce" section, vnav shouldn't be able to come on. in order for vnav to work, you have to have a couple extra things set up in your FMC. as for the "attitudes of some of the moderators", we would appreciate if you could give us some concrete examples. your age has absolutely nothing to do with anything here.

**Closed by ninjomcs** 2021-08-04 15:17 UTC
Labels: bug
