### ISSUE TITLE
[BUG] Systematic CTD at the start of stabilizer fuel tank transfer

### ISSUE THREAD

**Issue by Cassiano-Gunji** [saltysimulations/salty-747#181] opened 2021-04-21 21:11 UTC
**Version of the mod**

Dev version

**Describe the bug**

Every flight I try to fly with this plane results in a CTD at roughly one hour of real time. At that time, the plane has always been stable, under autopilot, on time acceleration 4x and in this condition for at least 5 minutes (haven't investigated this). I couldn't identify any other event, like proximity to waypoint, particular point of the globe, latitude, longitude or local time.

Edit: It seems now that it happens when the MAX FL readout from the FMC is about to change from FL299 to FL300. All these flights were attempted with all tanks full.

**Edit2: It is now clear that the CTD happens when the center main tank drops below 80 and the stabilizer fuel transfer should kick in.**

It has happened about four times in the last month, which is the total of flights I attempted with this mod, 100% of occurrences.

**To Reproduce**
1.  Have a full high IFR flight plan made in the sim.
2.  Have all fuel tanks filled. Start cold and dark (don't know if is relevant - I always start like this).
3.  Follow the plan until cruise. With autopilot on, engage time acceleration to 4x
4.  Wait for crash at roughly one hour since spawning. Seems to happen when the MAX FL readout on the second page of VNAV on the FMC changes from FL299 to FL300.

**Expected behavior**

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?
Only in the mod.

Your Discord:

**Comment by Cassiano-Gunji** [comment] 2021-04-23 05:37
Today I tried a new flight and noted that the sim seemed to crash at the moment the MAX FL readout on the second page of VNAV on the FMC is about to change from FL299 to FL300.

I was trying an endurance flight with all tanks full and was watching the MAX FL to perform the first altitude step. 

I'm updating the OP with this information.

**Comment by bscout9956** [comment] 2021-04-23 14:55
I did two intercontinental flights lately and couldn't reproduce this issue.

**Comment by ninjomcs** [comment] 2021-04-23 15:15
this doesn't seem related to the mod to me, as (afaik) something like the VNAV page would not CTD as if the display code encounters a runtime error only the display is usually rendered useless. there are a lot of outside factors that could cause CTDs. not ruling out the possibility of salty causing it, but i'd say it is unlikely.

**Comment by Cassiano-Gunji** [comment] 2021-04-24 05:53
Hello @bscout9956 , that's a good question. Of all my failed flights, this last one was the only one that I was actively watching the MAX FL readout. I don't know what the FMC computer does when it reaches a FL step (I was just trying to see that). Maybe I'll try at other steps. Will also try without other mods (yeah, I've noticed that some do indeed interfere with others).

I also can't say for shure that the MAX FL change was the cause. It just seemed to be. I'll try to investigate more. 

Hello @ninjomcs , I do understand your point. The problem is that Salty's mod is the only one that is consistently causing CTDs on my setup. Not even the experimental version of FlyByWire behaves this way. But I'll try a solo mod test as suggested by @bscout9956 just now. All I can say by now is that I tried 5 times to perform a stepped flight with full fuel tanks and the game crashed all of those times roughly at the same time.

**Comment by Cassiano-Gunji** [comment] 2021-04-24 07:37
Well, it's definite (sort of).

I removed all mods except Salty. Tried another flight with full fuel tanks and kept watching the MAX FL readout. The game crashed at MAX FL 299, at what seemed to be the time it would change to 300.

Another thing I noticed: The center main fuel tank was reading exactly 80.0 at CTD time. Maybe another clue. If I remember right, it still had a lot to go before starting the pumping of the stabilizer fuel tank.

**Comment by DesertRick13** [comment] 2021-04-24 16:51
I experienced  two CTD's this morning, one using VNAV (not a fan) and one using V/S. No particular pattern, the one VNAV was at FL205 when it quit, and the V/S was at FL100. Both were applying a setting for greater thrust, but I am not sure that has anything to do with it. I was using the newest master. I think I will try the release candidate and see what happens.

**Comment by 747-4EVER** [comment] 2021-04-24 17:47
> Well, it's definite (sort of).
> 
> I removed all mods except Salty. Tried another flight with full fuel tanks and kept watching the MAX FL readout. The game crashed at MAX FL 299, at what seemed to be the time it would change to 300.
> 
> Another thing I noticed: The center main fuel tank was reading exactly 80.0 at CTD time. Maybe another clue. If I remember right, it still had a lot to go before starting the pumping of the stabilizer fuel tank.
> 
> Counting 6 crashed flights in a row.

80,000Lbs is exactly when the stab transfer begins, I would suspect the transfer trigger as a possible cause for the CTD. From previous experience I know that incorrectly configured fuel systems are capable of crashing the sim, it won’t be anything to do with the VNAV display code...

However I tested the fuel transfer myself very recently on latest dev and had no problems. Can anyone else reproduce a crash when the stab begins transfer?

**Comment by DesertRick13** [comment] 2021-04-24 19:17
CYYZ-LFPG 

R/C for 3.0
210K lb Fuel. 82k in center tank, 20 K in stab tank, rest evenly distributed by weight in main tanks. Paid strict attention to the center tank/ stab tank combo with it being turned on about 2 minutes after takeoff. I was crossing about FL130 when the center tank reached 80.0 k lbs and poof, to desktop.  I think it is not the altitude, but rather the center tank and transfer mechanism which is the culprit after the latest MS update to aid with... wait for it... CTD's :)
Will try with just the main tanks.

**Comment by ninjomcs** [comment] 2021-04-24 19:47
we've had CTDs caused by the fuel stuff before, so yeah the stab tank transfer is probably the culprit

**Comment by DesertRick13** [comment] 2021-04-24 20:48
quick progress report
CYYZ-LFPG
R/C 1 for 3.0
Fuel in main tanks (none in center, stab or reserve)
presently still flying at FL330

**Comment by Cassiano-Gunji** [comment] 2021-04-24 22:09
That's it!

I've spawned on a random runway with takeoff configuration, engines running, all tanks full but center tank below 80. All fine. Then I opened the fuel (cheat) window and started playing with the center main tank. The first time I crossed from more than 80 to less than 80, instant CTD. It is clear now that the crash is related to the stabilizer fuel transfer.

**Comment by dcherrie** [comment] 2021-04-25 06:59
That would make sense as to why my ultra-long haul flights keep crashing when I'm going somewhere more 10 hours...

**Comment by dcherrie** [comment] 2021-04-25 10:18
@DesertRick13 get exactly the same result. 

https://www.youtube.com/watch?v=ONXLliZIHrw

**Comment by DesertRick13** [comment] 2021-04-25 12:29
From what I conclude: The bad news is that the 22k lb of fuel in the stab tank is inaccessible until fixed. The good news is that all the rest of the fuel system, even all the center tank is useable. So if the stab tank switch is avoided, most flights can still happen. For me San Juan to Hong Kong, no, but most, yes.

**Comment by Cassiano-Gunji** [comment] 2021-04-26 00:20
> @DesertRick13 get exactly the same result.
> 
> https://www.youtube.com/watch?v=ONXLliZIHrw

Wonderful capture! Much more to the point than my experiment!

**Comment by DesertRick13** [comment] 2021-04-26 04:12
@Cassiano-Gunji, thank you. It's a matter of  sharing experiences and  narrowing things down. Don't have the programming skills to fix it, but glad we have an idea as to what is going on.

**Comment by 747-4EVER** [comment] 2021-04-27 00:06
Narrowed down the OVRD pumps as the cause of the CTD. Crash does not occur if they are on during stab transfer as should be in normal operations.

Further investigation underway....

**Comment by DesertRick13** [comment] 2021-04-27 00:50
@747-4EVER 
To further test your conclusion.
Ground test, tanks 1, 2, 3, and 4 at 80 pct. (basically irrelevant).  Center tank at 81k lbs, stab tank full.
All pump switches ON except Stab and Main 2 and 3
started engines
Fuel flowed from Center tank
At arrow, turned on Stab, sim still working
Turned on Main 2 and 3 while xfer happening, sim still working
Turned off OVRD at Main 2 (forward, I believe), immediate CTD.

**Comment by DesertRick13** [comment] 2021-04-27 11:54
@747-4EVER In your investigation, it would also be nice to get the tank switch lights back as well. I know this is an ongoing thing because of Asobo updates.

**Comment by 747-4EVER** [comment] 2021-04-28 19:25
Fixed by #185.

**Closed by 747-4EVER** 2021-04-28 19:25 UTC
Labels: bug
