### ISSUE TITLE
ND Weather Display

### ISSUE THREAD

**Issue by Rijtim1** [saltysimulations/salty-747#355] opened 2021-11-13 15:48 UTC
### Version

Latest Dev

### Describe the bug

If you have weather turned on in the ND, and then switch to an external camera, when you come back to the flight deck view, the weather is not displayed anymore in the ND. The weather still shows up as selected, but weather data is not visible. an 

### Expected behaviour

The weather data should be visible in the ND when switching from external camera view to internal camera view.

### Steps to reproduce

1. Select weather on ND.
2. Go to external View
3. Come back to the internal view

### Additional information

Deactivating weather and reactivating it solves the issue.

### Your Discord

BaronFalcon#3677

**Comment by 747-4EVER** [comment] 2021-12-06 08:28
Duplicate of #296

**Closed by 747-4EVER** 2021-12-06 08:28 UTC
Labels: bug
