### ISSUE TITLE
Mod very bugy after the latest Update. 

### ISSUE THREAD

**Issue by mark1606** [saltysimulations/salty-747#120] opened 2020-12-24 15:47 UTC
**Version of the mod**
Latest Stable Version

**Describe the bug**
Apu will not start, most Efis pages not showing or working properly, Some of the fuel pumps are not responsive, seat belt knob will not turn, engines will not start (no apu)

**To Reproduce**
1. 
2. 
3. 
4. 

**Additional information**
Bugs not showing in default 747-8 but using mod brings back FMC screens that are blank in default ver since the update. 

Your Discord:

**Comment by ninjomcs** [comment] 2020-12-24 16:10
First part of this is fixed in #119. Regarding the FMC screens, the reason is a conflict with the A32NX. For the time being, uninstall it if you want to use the 747 (default included). We’ve already worked out the cause.

**Comment by mark1606** [comment] 2020-12-24 16:18
Thank you.

**Closed** 2020-12-27 13:47 UTC
Labels: bug
